openapi: 3.0.3
info:
  title: Choreo Sample - Book List - SpringBoot REST API Service
  description: >-
    This is a sample API specification for a simple coffee shop
    written in Nodejs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Choreo
  url: https://choreo.dev
servers:
  - url: http://localhost:8080
tags:
  - name: index
    description: In-memory coffee shop API
paths:
  /index:
    summary: index
    get:
      operationId: index
      tags:
        - index
      responses:
        "200":
          description: Successful operation
